### PR TITLE
[WFLY-14013] "javax.servlet.error.message" also should be transformed to "jakarta.servlet.error.message" in jakarta-direct.properties

### PR DESCRIPTION
**Pull request by scottmarlow**
https://issues.redhat.com/browse/WFLY-14013

@jfdenise where are the latest `EE-9 galleon-plugins` kept these days?  Also, which branch should I build locally to try a Batavia change?

Thanks,
Scott

### CODE REVIEW

**Review by ropalka — CHANGES_REQUESTED** [review]
In JIRA you mention also javax.servlet.error.exception_type, we should add it

**Comment by jfdenise** [comment]
@scottmarlow , the branch is : https://github.com/wildfly/galleon-plugins/tree/5.x, the latest plugin is https://github.com/wildfly/galleon-plugins/releases/tag/5.0.0.Alpha4

**Comment by scottmarlow** [comment]
> In JIRA you mention also javax.servlet.error.exception_type, we should add it

Thanks Richard,I will add an entry for that, whether javax.servlet.error.exception=>javax.servlet.error.exception covers `javax.servlet.error.exception_type` or not, it will be more clear to have an entry for `javax.servlet.error.exception_type`

**Comment by scottmarlow** [comment]
> @scottmarlow , the branch is : https://github.com/wildfly/galleon-plugins/tree/5.x, the latest plugin is https://github.com/wildfly/galleon-plugins/releases/tag/5.0.0.Alpha4

Thanks Jean-François!

**Comment by scottmarlow** [comment]
@ropalka are there further changes needed? If not, I think this is ready to be merged.  Thanks!

**Review by ropalka — APPROVED** [review]
It's OK Scott. Sorry for delay.

**Pull request merged**
