### PR TITLE
[ISSUE-32] Add support to transform JBoss modules

### PR DESCRIPTION
**Pull request by jfdenise**
API to transform module.xml, module filesystem layout and optionally artifacts.
The default modules mapping has been added to the api module, I guess that it would be needed during class transformation to inject the transformed JBoss module name into deployment.

Bump junit version to 4.

### CODE REVIEW

**Comment by jfdenise** [comment]
@ropalka @scottmarlow , the modules transformation API.

**Comment by ropalka** [comment]
> I guess that it would be needed during class transformation to inject the transformed JBoss module name into deployment.

Good point @jfdenise

**Comment by scottmarlow** [comment]
If we make this change, I think that we will also need to update jboss-deployment-structure.xml + MANIFEST.MF in applications to use the updated module names (if they statically depend on certain system modules).  I'm not sure how well supported that is but it is in the [community doc](http://docs.wildfly.org/19.1/Developer_Guide.html).

@bstansberry any feedback on this pr to change system module names to use jakarta instead of javax?

**Comment by scottmarlow** [comment]
>     I guess that it would be needed during class transformation to inject the transformed JBoss module name into deployment.
> 
> Good point @jfdenise ! That implies it is not bad idea to merge both configurations in near future then. WDYT @scottmarlow ?
> 

See my previous comment, are we talking about the same thing, of updating deployment MANIFEST.MF and/or jboss-deployment-structure.xml?

**Comment by jfdenise** [comment]
@scottmarlow , I opened this PR to offer this capability to batavia project but I am not convinced that we will make use of it in the galleon provisioning a EE9 server. @bstansberry was suggesting that some aliases would be injected and the module names would be already modified.

**Comment by jfdenise** [comment]
@scottmarlow , related to changing the deployment. I was under the assumption that the application would be built against EE9 (so not transformed) and already referencing the EE9 module names (if needed) that wildfly would document.

**Comment by scottmarlow** [comment]
> @scottmarlow , I opened this PR to offer this capability to batavia project but I am not convinced that we will make use of it in the galleon provisioning a EE9 server. @bstansberry was suggesting that some aliases would be injected and the module names would be already modified.

Hmm, adding aliases for the javax modules could address my concern (if this is used in the galleon provisioning of a EE9 server.)

**Comment by scottmarlow** [comment]
> @scottmarlow , related to changing the deployment. I was under the assumption that the application would be built against EE9 (so not transformed) and already referencing the EE9 module names (if needed) that wildfly would document.

I did hear that others are using the Eclipse Transformer to transform the Jakarta TCK in various ways for EE 9 testing, the[ most recent discussion is here.](https://github.com/eclipse-ee4j/jakartaee-tck/pull/246).

After reading feedback above, I am fine with this change.  +1

**Pull request merged**
