### PR TITLE
updated merge with open-liberty/dev/wlp-jakartaee-transform/rules/jakarta-direct.properties with some reordering to allow easy future merging as needed

### PR DESCRIPTION
**Pull request by scottmarlow**
Signed-off-by: Scott Marlow <smarlow@redhat.com>

Moved some entries around, sorted some and synced up again with pull request that I will create for OpenLiberty

### CODE REVIEW

**Comment by scottmarlow** [comment]
Just opened https://github.com/OpenLiberty/open-liberty/issues/14995

**Comment by scottmarlow** [comment]
Since the license terms of the jakarta-direct.properties in Batavia is Apache but OpenLiberty is using EPL, we could consider a multiple license approach similar to https://github.com/jboss/jboss-jakarta-el-api_spec/blob/master/LICENSE.md where users can decide the license to use (Apache which has more freedom versus EPL which is more restrictive).  We may need some advice on this.

**Comment by scottmarlow** [comment]
@bstansberry Batavia is using the ASL 2.0 and OpenLiberty uses Eclipse Public License 1.0.  I'm thinking of adding EPL 1.0 as a second (ASL 2,0 or EPL 1.0) license to Batavia.  Not sure if that is really needed though for sharing these properties with OpenLiberty.

**Review by bstansberry — APPROVED** [review]
AFAICT this just reorganizes and adds some comments to organize the groups. So that seems fine.

**Comment by bstansberry** [comment]
@scottmarlow if you and Richard want to add EPL that's fine with me.

**Comment by ropalka** [comment]
I'm fine with dual licensing @scottmarlow & @bstansberry .

**Pull request merged**
