### PR TITLE
[ISSUE-69] Fixing jasper library transformation issues

### PR DESCRIPTION
**Pull request by ropalka**
https://github.com/wildfly-extras/batavia/issues/69

### CODE REVIEW

**Comment by scottmarlow** [comment]
Hi Richard, any suggestions for how I should review this change for correctness?  Did you carefully write this pull request after inspecting jasper?  Or did you go by a jira that perhaps explains the needed transformation?

I am starting to run Jakarta EE 9 Platform TCK testing which includes JSP tests which may help us with testing this change.  Will likely need to merge this and when it shows up in use on https://github.com/bstansberry/wildfly (ee-9 branch) should be able to run the JSP tests.  

Currently I'm looking at https://issues.redhat.com/browse/WFLY-13837 for a TCK JSP test reference to an old J2EE DTD that I don't see in the TCK source, so not yet sure of what is going on.

**Comment by ropalka** [comment]
Hello @scottmarlow - there are two ways how to validate the correctness of this proposed change set.

First, there was a failing test in weld core TCK. Steps to reproduce it are:
---
1) Build EE 9 WFLY
2) Checkout Weld from git@github.com:weld/core.git
3) Build weld and set + update WFLY (to use weld snapshot)

* cd weld/core
* mvn clean install -DskipTests
* export JBOSS_HOME=/path/to/ee9/variant/of/wfly
* mvn clean package -Pupdate-jboss-as -Dtck -f jboss-as/pom.xml
* mvn clean verify -Dincontainer -Dtest=InjectionIntoNonContextualComponentTest#testInjectionIntoJSFManagedBean -f jboss-tck-runner/pom.xml
---

Second manually transform jasper.jar file using Eclipse transformer manually and inspect all class files and their UTF-8 constants if they don't contain "javax." string.

**Comment by ropalka** [comment]
Or you can run whole weld TCK not just one test:
---
mvn clean verify -Dincontainer -f jboss-tck-runner/pom.xml
---

**Comment by scottmarlow** [comment]
Thanks @ropalka I am updating the (Jenkins) EE 9 CDI testing to follow your steps (I needed to update them to work), so I have, please let me know if any of it differs from what you are using:

```
export MAVEN_VERSION=3.2.5
export M2_HOME=/qa/tools/opt/maven-${MAVEN_VERSION}
export PATH=$M2_HOME/bin:$PATH
MAVEN_OPTS="-XX:+UseGCOverheadLimit -Xmx1024m -Xms512m -XX:PermSize=256m -XX:MaxPermSize=768m -Dorg.apache.maven.user-settings=/qa/m2/settings.xml -Dmaven.repo.local=/qa/m2/repository"
export MAVEN_OPTS
export JBOSS_DIR=wildfly
export JBOSS_ZIP=./wildfly.zip

unzip wildfly.zip > /dev/null && rm -f wildfly.zip
mv wildfly-* $JBOSS_DIR

cd $WORKSPACE
git clone https://github.com/weld/core.git weld
cd weld
mvn clean install -DskipTests
export JBOSS_HOME=${WORKSPACE}/${JBOSS_DIR}
mvn clean package -Pupdate-jboss-as -Dtck -f jboss-as/pom.xml   
mvn clean verify -Dincontainer -f jboss-tck-runner/pom.xml
```
However, the `mvn clean verify -Dincontainer  -f jboss-tck-runner/pom.xml` fails with:
```
Building CDI TCK runner (2.0) for Weld (WildFly) 4.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------

[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ weld-jboss-runner-tck ---
[INFO] Deleting /mnt/hudson_workspace/workspace/jakartaee-ee9/cdi/weld/jboss-tck-runner/target
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-java-version) @ weld-jboss-runner-tck ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-maven-version) @ weld-jboss-runner-tck ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-jboss-home-is-set) @ weld-jboss-runner-tck ---
[INFO] 
[INFO] --- build-helper-maven-plugin:1.12:maven-version (default) @ weld-jboss-runner-tck ---

[INFO] 
[INFO] --- build-helper-maven-plugin:1.12:parse-version (default) @ weld-jboss-runner-tck ---
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-resources) @ weld-jboss-runner-tck ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.985 s
[INFO] Finished at: 2020-09-10T10:10:39-04:00
[INFO] Final Memory: 21M/495M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.1.0:copy-resources (copy-resources) on project weld-jboss-runner-tck: Unable to parse configuration of mojo org.apache.maven.plugins:maven-resources-plugin:3.1.0:copy-resources for parameter includes: Cannot assign configuration entry 'includes' with value 'standalone-activemq-embedded.xml' of type java.lang.String to property of type java.util.List -> [Help 1]
```

I'll work through resolving this but if you do notice anything different between what I did and your running of the CDI TCK with EE-9 WF, please let me know.

I will merge this pr now.

Thanks,
Scott

**Comment by ropalka** [comment]
I don't see difference @scottmarlow , just that I'm using Maven 3.6.3 and not 3.2.5.

**Comment by scottmarlow** [comment]
thanks Richard, good to know!

**Pull request merged**
