### PR TITLE
[ISSUE-22] Put transformed classes into appropriate packages

### PR DESCRIPTION
**Pull request by ropalka**

### CODE REVIEW

**Comment by ropalka** [comment]
When I was playing with your asm transformer I discovered an issue - it is not some transforming someclasses. I tested it with servlet-2.3-api.jar and I can see two classes javax/servlet/jsp/tagext/TryCatchFinally.class & javax/servlet/SingleThreadModel.class were not transformed.

**Comment by scottmarlow** [comment]
https://github.com/wildfly-extras/batavia/pull/24 doesn't look right, I'll merge your pr and check again.

**Comment by scottmarlow** [comment]
Thanks for these changes, looks great.  I'll create a new pr or adjust https://github.com/wildfly-extras/batavia/pull/24 for the issue you mentioned.

**Comment by ropalka** [comment]
Thanks for review & merge @scottmarlow

**Pull request merged**
