### PR TITLE
Rename packages from org.wildfly.transformer.* to org.wildfly.extras.transformer.*

### PR DESCRIPTION
**Pull request by ropalka**

### CODE REVIEW

**Comment by scottmarlow** [comment]
Does this address an open issue?  If not, could you please briefly summarize?

**Comment by ropalka** [comment]
There Is no open issue related to this PR @smarlow. When I released Alpha1 of Batavia, I changed Batavia's maven coordinates. This PR just synchronizes packages with those maven coordinates. Consider this PR a cosmetic change.

**Comment by scottmarlow** [comment]
@ropalka it looks like I created a conflict when I merged impl/ecl/src/main/resources/org/wildfly/transformer/eclipse/jakarta-direct.properties

**Comment by scottmarlow** [comment]
@ropalka I can rebase easily but trying to merge via "git mergetool" didn't seem to work as expected.  Any suggestions?

**Comment by scottmarlow** [comment]
Thanks @ropalka

**Comment by ropalka** [comment]
I see you resolved the problem in the meantime. Thanks for review @smarlow

**Pull request merged**
