### PR TITLE
All transformer implementations are in org.wildfly.transformer subpackages

### PR DESCRIPTION
**Pull request by ropalka**
I propose to move transformer implementations from org. to com. package @scottmarlow

### CODE REVIEW

**Comment by scottmarlow** [comment]
@ropalka isn't com. packages typically for commercial software products and org.* for non-profit or open source?

**Comment by scottmarlow** [comment]
like for www.redhat.com, we could use com.redhat.product

**Comment by ropalka** [comment]
Let's discuss it @scottmarlow . My point of view is 
 * org namespace is for API
 * com is for implementation

Consider Open JDK project as an example. It is open source.
It contains java & javax packages (defacto API packages)
and everything that starts with com. is considered implementation detail
and it is not recommended to import these classes.

**Comment by ropalka** [comment]
com.redhat.transformer.asm
com.redhat.transformer.nodeps

is also fine

**Comment by scottmarlow** [comment]
com.wildfly doesn't sound like a company name though, org.wildfly is more typical for our projects.

**Comment by scottmarlow** [comment]
com.redhat does sound like Red Hat specific code, my preference is to be vendor neutral.

**Comment by ropalka** [comment]
OK @scottmarlow - I changed this proposal PR accordingly

**Comment by scottmarlow** [comment]
Thanks, looks good @ropalka

**Pull request merged**
